### ISSUE TITLE
Поехали

### ISSUE THREAD

**Issue by AndreiPonomarev** [ZuevKirill95/Simon_Electronic_Game#17]
Создай новый отладочный компонент computerSequense
Он будет такой же как sequenceContainer, но в нем будет последовательность, сгенеренная игрой.

Кнопка в центре будет кроме сброса начинать новую игру.
Нужно добавить функции addComputerStep, checkSequense

Процесс такой:

`resetSequence-> addComputerStep -> addSequenceStep ->  checkSequense `
дальше проверка соответствия и либо снова  
`addComputerStep -> addSequenceStep ->  checkSequense `
либо новый экшн endGame 
который выведет сообщение об окончании игры.

В стор добавляем computerSequense, gameState - текущее состояние игры: null/active/finished
Соответсвенно в экшенах проверяем computerSequense === gameSequence

**Comment by ZuevKirill95** [comment]
Отдельно ветку нужно создавать?

**Comment by AndreiPonomarev** [comment]
Ветки не надо. Это пока та же самая фича.
