### ISSUE TITLE
react

### ISSUE THREAD

**Issue by AndreiPonomarev** [ZuevKirill95/Simon_Electronic_Game#4]
Дальше создаешь отдельный проект и изучаешь [https://maxfarseer.gitbooks.io/react-course-ru/content/](url)
Поймешь чистый реакт - поедем дальше

**Comment by ZuevKirill95** [comment]
Извиняюсь) Я только сейчас прочитал весь туториал
Почему-то подумал, что можно не коммитить, в следующий раз буду)
