### ISSUE TITLE
Прикручиваем реакт.

### ISSUE THREAD

**Issue by AndreiPonomarev** [ZuevKirill95/Simon_Electronic_Game#7]
Делаешь новую ветку: feature/react-app.
Готовишь пустой хелловорлд на реакте.
Делаешь пулл реквест.
Дальше будем прикручивать к ней игрульку.

**Comment by ZuevKirill95** [comment]
Хорошо) 
Не могу сделать пул реквест, не могу понять, что он от меня хочет
Вот что пишет"Choose different branches or forks above to discuss and review changes."

**Comment by AndreiPonomarev** [comment]
Сначала откати коммит. Потом пушься в новую ветку
